version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - benthos
  
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper 
    networks:
      - benthos
  mqtt:
    image: eclipse-mosquitto:1.6.12
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/volume/mosquitto/config
      - ./mosquitto/data:/volume/mosquitto/data
      - ./mosquitto/log:/volume/mosquitto/log

  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/volume/nodered/data

  mqttkafkabridge:
    image: unifactmanufacturinghub/mqttkafkabridge:linuxamd0.3
    environment:
      KAFKA_BROKER: kafka:9092
      MQTT_BROKER: mqtt://mqtt:1883
    depends_on:
      - kafka
      - mqtt

networks:
  benthos:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.29.0.0/16"
