version: '3.8'
 
services:
  node-red:
    container_name: nodered
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
      - "10502:10502"
    links:
      - redis
    networks:
     - benthos
 
  MQTT:
    container_name: mqtt
    image: eclipse-mosquitto
    command: mosquitto -c /mosquitto-no-auth.conf
    tty: true
    restart: unless-stopped
    ports:
      - 1883:1883
      - "9001:9001"
    networks:
      - benthos
  
  kafka:
    container_name: kafka-benthos
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - benthos
    environment:
     # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
      # Listeners
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka-benthos:9092,CONTROLLER://kafka-benthos:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://192.168.50.111:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_USER=user
      - KAFKA_CONTROLLER_PASSWORD=bitnami
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=bitnami   
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE= true

  mssql-db:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password99"
      ACCEPT_EULA: "Y"
  benthos-umh:
    build: ./
    image: unifactmanufacturinghub/benthos:linuxamd0.6
    #unifactmanufacturinghub/benthos-linux386:latest
    #unifactmanufacturinghub/benthos-linuxamd64:latest
    volumes:
       - /home/btl/Downloads/streams:/streams
    ports:
      - 4195:4195
    networks:
      - benthos
 
  redis:
    container_name: redis
    image: redis
    # command: redis-server --requirepass superpassword
    restart: unless-stopped
    tty: true
    ports:
      - 6379:6379
    networks:
      - benthos
  mqttkafkabridge:
    image: unifactmanufacturinghub/mqttkafkabridge:linuxamd0.3
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      KAFKA_CLIENT_ID: benthos
      KAFKA_USE_SSL: false
      MQTT_BROKER_URL: mqtt:1883
      MQTT_CERTIFICATE_NAME: NO_CERT
      MY_POD_NAME: benthos
      MQTT_TOPIC: ia/raw/opcua/#
      KAFKA_LISTEN_TOPIC: ia/raw/opcua/#
    depends_on:
      - kafka
      - MQTT
    networks:
      - benthos
#  opcuasimulator:
#     container_name: opcsimulator1
#     image: unifactmanufacturinghub/opcsimulator:0.0.1
#     ports:
#       - 46010:46010
#     networks:
#       - benthos
 
  #influxdb:
  #  container_name: influxdb
  #  image: influxdb
  #  ports:
  #    - 8086:8086
  #  networks:
  #    - benthos
 
 
networks:
  benthos:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.29.0.0/16"