version: '3'
 
services:
  benthos-umh:
    build: ./
    image: benthos
    volumes:
       - /home/btl/Downloads/streams:/streams
    ports:
      - 4195:4195
    networks:
      - benthos
 
  redis:
    container_name: redis
    image: redis
    # command: redis-server --requirepass superpassword
    restart: unless-stopped
    tty: true
    ports:
      - 6379:6379
    networks:
      - benthos
 
  node-red:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
      - "10502:10502"
    links:
      - redis
    networks:
     - benthos
 
  MQTT:
    container_name: mqtt
    image: eclipse-mosquitto
    command: mosquitto -c /mosquitto-no-auth.conf
    tty: true
    restart: unless-stopped
    ports:
      - 1883:1883
    networks:
      - benthos
  mssql-db:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password99"
      ACCEPT_EULA: "Y"

  #opcua:
  #   container_name: opcsimulator1
  #   image: opcsimulator
  #   ports:
  #     - 46010:46010
  #   networks:
  #     - benthos
 
  #influxdb:
  #  container_name: influxdb
  #  image: influxdb
  #  ports:
  #    - 8086:8086
  #  networks:
  #    - benthos
 
 
networks:
  benthos:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.29.0.0/16"