# Copyright 2023 UMH Systems GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
input:
  opcua:
    endpoint: "opc.tcp://localhost:46010"
    nodeIDs:
      - '{"1": [{"node": "ns=2;s=Pressure", "name":"Pressure", "mtopic":"runtime","group": "D001", "db": "mssql", "historian": "influx", "sqlSp": "sp_sql_logging"}]}'
      - '{"2": [{"node": "ns=2;s=Tem perature", "name":"Temperature", "mtopic":"runtime", "group": "D002", "db": "mssql", "historian": "influx", "sqlSp": "sp_sql_logging"}]}'
      - '{"1": [{"node": "ns=2;s=TwinCat.AFP-DC1.D001.Shot_Signal","dataType": "bool","name": "D001_shots","logging_sql": "false","logging_influx": "true","group": "D001", "db": "mssql", "historian": "influx", "sqlSp": "sp_sql_logging"}]},"group": "D001", "db": "mssql", "historian": "influx", "sqlSp": "sp_sql_logging"}]}'
    subscribeEnabled: true
    insecure: true

pipeline:
  processors:
    - bloblang: |
        root = meta("Message").parse_json()
        root.timestamp_ms = (timestamp_unix_nano() / 1000000).floor()
        root.group = meta("group")
        root.db = meta("db")
        root.historian = meta("historian")
        root.sqlSp = meta("sqlSp")
output:
  mqtt:
    urls:
      - 'localhost:1883'
    topic: 'ia/raw/opcua/${! meta("opcua_path") }'
    client_id: benthos-umh